CREATE DATABASE IF NOT EXISTS teamweb2020 CHARACTER SET UTF8 COLLATE UTF8_BIN;
CREATE TABLE IF NOT EXISTS teamweb2020.ACCOUNT(NAME VARCHAR(14) NOT NULL, ACCOUNT CHAR(10) NOT NULL, EMAIL VARCHAR(14) NOT NULL UNIQUE KEY, PASSWD CHAR(10) NOT NULL, PRIMARY KEY (ACCOUNT) );


SELECT * FROM teamweb2020.ACCOUNT;
INSERT INTO teamweb2020.account(name,account,email,passwd) VALUE('小明','A12345','cat@kitty.com','Aa123');
DELETE FROM teamweb2020.ACCOUNT WHERE ACCOUNT LIKE "*";

SELECT * FROM teamweb2020.mb;
